spring.application.name=inventory

# BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/db_inventory?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# LOGS
logging.level.org.hibernate.SQL=debug

# PUERTO
server.port=8081